# Generated by Django 5.2.1 on 2025-05-18 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner'], name='projects_pr_owner_i_dea3a1_idx'),
        ),
    ]
