# Generated by Django 5.2.1 on 2025-05-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_comment_tasks_comme_id_7f0880_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
