# Generated by Django 5.2.1 on 2025-05-20 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_sprint_taskstatus'),
        ('tasks', '0005_task_actual_hours_task_estimated_hours'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_status__0039af_idx',
            old_name='tasks_task_status_4a0a95_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.sprint'),
        ),
        migrations.AddField(
            model_name='task',
            name='story_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.taskstatus'),
        ),
    ]
