# Generated by Django 5.2.1 on 2025-05-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_unique_together_taskhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskhistory',
            old_name='fields',
            new_name='field',
        ),
    ]
